server:
  port: 49000
eureka:
  client:
    #???????????? eureka server ????true ??????????eureka server ????????false
    register-with-eureka: false
    #???????eureka server ????????? ????true ?????????????? ????????????server?????
    fetch-registry: false
    service-url:
      #??????eureka server ???????? ??????????????????????????? ??????????????,???
      default-zone: http://127.0.0.1:49000/eureka