server:
  port: 49000
eureka:
  client:
    #表示是否将自己注册到eureka server 默认为true 由于此次架构 eureka设置为单点 ，并且该服务为eureka server 因此设置为false
    register-with-eureka: false
    #表示是否从eureka server 获取注册信息 默认为true 因为这是一个单点 不需要同步其他 eureka server 节点的数据 故设置为false
    fetch-registry: false
    service-url:
      #设置与 eureka server交互地址 查询服务和注册服务都需要依赖这个地址 多个地址之间可以用,分隔
      default-zone: http://127.0.0.1:49000/eureka